# Training a multilayer perceptron 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Import tf, keras, layers, models, optimizers, and datasets to build our own mlp
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers, utils, datasets

#### Define the classes

In [2]:
NUM_CLASSES = 10

#### Prepare data

In [3]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()
# In this case, the x values are the pixel values out of 255

In [4]:
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

#  convert classes into one-hot encoded vectors
y_train = utils.to_categorical(y_train, NUM_CLASSES)
y_test = utils.to_categorical(y_test, NUM_CLASSES)

In [5]:
print(x_train[:1])
print(x_test[:1])

[[[[0.23137255 0.24313726 0.24705882]
   [0.16862746 0.18039216 0.1764706 ]
   [0.19607843 0.1882353  0.16862746]
   ...
   [0.61960787 0.5176471  0.42352942]
   [0.59607846 0.49019608 0.4       ]
   [0.5803922  0.4862745  0.40392157]]

  [[0.0627451  0.07843138 0.07843138]
   [0.         0.         0.        ]
   [0.07058824 0.03137255 0.        ]
   ...
   [0.48235294 0.34509805 0.21568628]
   [0.46666667 0.3254902  0.19607843]
   [0.47843137 0.34117648 0.22352941]]

  [[0.09803922 0.09411765 0.08235294]
   [0.0627451  0.02745098 0.        ]
   [0.19215687 0.10588235 0.03137255]
   ...
   [0.4627451  0.32941177 0.19607843]
   [0.47058824 0.32941177 0.19607843]
   [0.42745098 0.28627452 0.16470589]]

  ...

  [[0.8156863  0.6666667  0.3764706 ]
   [0.7882353  0.6        0.13333334]
   [0.7764706  0.6313726  0.10196079]
   ...
   [0.627451   0.52156866 0.27450982]
   [0.21960784 0.12156863 0.02745098]
   [0.20784314 0.13333334 0.07843138]]

  [[0.7058824  0.54509807 0.3764706 ]
   [0.6

#### Build the model

In [ ]:
# The Input layer defines the input shape of the data. 
# images of height 32, width 32, and 3 color channels (RGB).
input_layer = layers.Input((32, 32, 3))

# reshapes the input data into a 1D array before feeding it into the subsequent fully connected layers.
x = layers.Flatten()(input_layer)

# Two Dense layers follow the Flatten layer, with 200 and 150 neurons, respectively. 
x = layers.Dense(200, activation="relu")(x)
x = layers.Dense(150, activation="relu")(x)

# Final dense layer
# Serves as the output layer, consisting of NUM_CLASSES neurons and utilizes the softmax activation function
# The softmax activation normalizes the output into a probability distribution across the classes

output_layer = layers.Dense(NUM_CLASSES, activation="softmax")(x)

# The models.Model() function combines the defined layers into a functional Model.
model = models.Model(input_layer, output_layer)

#  provides a summary of the model architecture
model.summary()